name: Start Typesense server

on: [push, pull_request]

jobs:
  typesense-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typesense-version: [0.23.1]

    name: Start Typesense Server v${{ matrix.typesense-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start Typesense Server
        uses: ./
        with:
          typesense-version: ${{ matrix.typesense-version }}

      - name: Curl Typesense
        run: sleep 10 && curl http://localhost:8108/health
